# Generated by Django 6.0.4 on 2026-04-19 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_Name', models.CharField(max_length=250)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=9)),
                ('user_limit', models.IntegerField()),
                ('colony_limit', models.IntegerField()),
                ('is_unlimit_users', models.BooleanField(default=False)),
                ('is_unlimit_colony', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('ceo_name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_subscribe', models.BooleanField(default=False)),
                ('expire_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_by_subscription_package', to='managements.subscribeplan')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('industry', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('location_url', models.URLField(blank=True, null=True, verbose_name='colony_location')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMechanary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('serial_number', models.CharField(max_length=250)),
                ('purchase_year', models.DateField()),
                ('condition', models.CharField(max_length=250)),
                ('next_nervice', models.CharField(max_length=250)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='inactive', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_reps',
            field=models.ManyToManyField(related_name='customers', to='managements.salesrepresentative'),
        ),
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('region', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused')], default='paused', max_length=250)),
                ('location_url', models.URLField(verbose_name='colony_location')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('colony_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.company')),
                ('customers', models.ManyToManyField(blank=True, related_name='colonies', to='managements.customer')),
                ('sales_reps', models.ManyToManyField(blank=True, related_name='colonies', to='managements.salesrepresentative')),
            ],
        ),
        migrations.CreateModel(
            name='VisitColony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_visited', models.BooleanField(default=True)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.colony')),
                ('completed_customers', models.ManyToManyField(blank=True, related_name='completed_colonies', to='managements.customer')),
                ('pending_customers', models.ManyToManyField(blank=True, related_name='pending_colonies', to='managements.customer')),
            ],
        ),
    ]
