# Generated by Django 6.0.4 on 2026-08-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_company_is_business_company_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_business',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_public',
        ),
        migrations.AddField(
            model_name='colony',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colony',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
