# Generated by Django 6.0.4 on 2026-08-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_remove_company_is_business_remove_company_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='location_url',
            field=models.URLField(blank=True, null=True, verbose_name='colony_location'),
        ),
    ]
