# Generated by Django 6.0.4 on 2026-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_alter_colony_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_buiesness',
            field=models.BooleanField(default=False),
        ),
    ]
